name: appr

on: [push]

jobs:
  awscli:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v1
    - name: Login
      run: |
        echo ${{ secrets.DOCKERHUB_PASSWORD }} | \
          docker login -u drmjo --password-stdin
    - name: 0.7.4
      env:
        VERSION: 0.7.4
        SHA256SUM: 2ff148a900c5a153ea444bebac169001397ebfb466789356cd0f077b48e7d91c
        APP: appr
      run: |
        make build
        make push