name: awscli

on: [push]

jobs:
  awscli:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v1
    - name: Login
      run: |
        echo ${{ secrets.DOCKERHUB_PASSWORD }} | \
          docker login -u drmjo --password-stdin
    - name: 1.16.309
      env:
        VERSION: 1.16.309
        APP: awscli
      run: |
        make build
        make push