name: base

on: [push]

jobs:
  base:
    needs:
    - awscli
    - appr
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v1
    - name: Login
      run: |
        echo ${{ secrets.DOCKERHUB_PASSWORD }} | \
          docker login -u drmjo --password-stdin
    - name: base
      env:
        VERSION: buster
        AWS_CLI_VERSION: 1.16.309
        APP: base
      run: |
        make build
        make push