name: Build

on: [push]

runs-on: ubuntu-latest

jobs:
  kubectl:
    steps:
    - name: Git checkout
      uses: actions/checkout@v1

    - name: DIR?
      run: |
        pwd
        ls -la
    - name: build
      env:
        SHA256SUM: 85548a113564f34e5e60253f8b1616eed0e8c171a6869668beb93d1f97fbea8e
        VERSION: 1.14.8
        APP: kubectl
      run: make build