name: Build

on: [push]

jobs:
  build-base:

    runs-on: ubuntu-latest

    steps:
      - name: interpolate
        run: |
          echo $FINAL
          echo ${{ format('{0}_{1}', ${{ env.FIRST }}, ${{ env.SECOND }}) }}
          echo $SECOND_2
          echo $FIRST
          echo $SECOND
        env:
          FIRST: a
          SECOND: b
          FINAL: format('{0}_{1}', ${{ env.FIRST }}, ${{ env.SECOND }} )
          SECOND_2: ${{ env.SECOND }}
    # - name: Git checkout
    #   uses: actions/checkout@v1
    # - name: DIR?
    #   run: |
    #     pwd
    #     ls -la
    # - name: Docker
    #   env:
    #     FQIN: drmjo/kubectl:1.14.8
    #     SHA256SUM: 85548a113564f34e5e60253f8b1616eed0e8c171a6869668beb93d1f97fbea8e
    #     VERSION: 1.14.8
    #     APP: kubectl
    #   run: |
    #     docker build \
    #       -t $FQIN \
    #       --build-arg CI_REGISTRY_IMAGE=$CI_REGISTRY_IMAGE \
    #       --build-arg SHA256SUM=$SHA256SUM \
    #       --build-arg VERSION=$VERSION \
    #       $APP