name: Build

on: [push]

jobs:
  build-base:

    runs-on: ubuntu-latest

    steps:

    - name: Has Make?
      run: make --version
    - name: Docker
      run: 	docker build \
            -t ${FQIN} \
            --build-arg CI_REGISTRY_IMAGE=${CI_REGISTRY_IMAGE} \
            --build-arg SHA256SUM=${SHA256SUM} \
            --build-arg VERSION=${VERSION} \
            $(app)
      
    # - uses: actions/checkout@v1

    # - name: Run a one-line script
    #   run: echo Hello, world!

    # - name: Run a multi-line script
    #   run: |
    #     echo Add other actions to build,
    #     echo test, and deploy your project.
