name: Build All

on: [push]

env:
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

jobs:
  helm:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v4
    - name: Build helm ${{ matrix.version }}
      uses: ./.github/actions/build
      with:
        app: helm
        version: 3.18.6
        sha: 3f43c0aa57243852dd542493a0f54f1396c0bc8ec7296bbb2c01e802010819ce

  terragrunt:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v4
    - name: Build terragrunt ${{ matrix.version }}
      uses: ./.github/actions/build
      with:
        app: terragrunt
        version: 0.85.1
        sha: 7662eed6fa23cff352c996600c1cfdab085f19161cb6bd528e4125f31507f712

  packer:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v4
    - name: Build packer ${{ matrix.version }}
      uses: ./.github/actions/build
      with:
        app: packer
        version: 1.14.2
        sha: cfefdea4ac580eba7b254ef34d25b756d4961741004e3e701a1476594d13e64a

  kubectl:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - version: 1.35.2
            sha: 924eb50779153f20cb668117d141440b95df2f325a64452d78dff9469145e277
          - version: 1.34.5
            sha: 6a17dd8387783b3144a65535e38d02c351027e9718ea34a6c360476cb26d28bb
          - version: 1.33.9
            sha: 9e33e3234c0842cd44a12c13e334b4ce930145ea84b855ce7cc0a7b6bc670c22
          - version: 1.32.13
            sha: db2ae479a63f3665d7f704ab18c0d4d4050144237980763221835b7305703c4c
          - version: 1.31.14
            sha: 8791ec7c8966b61420d55103a5fb948de9f0ca3d7306d789734975ad9704bdb0
          - version: 1.30.2
            sha: c6e9c45ce3f82c90663e3c30db3b27c167e8b19d83ed4048b61c1013f6a7c66e
          - version: 1.29.6
            sha: 339553c919874ebe3b719e9e1fcd68b55bc8875f9b5a005cf4c028738d54d309
          - version: 1.28.11
            sha: 1dba63e1a5c9520fc516c6e817924d927b9b83b8e08254c8fe2a2edb65da7a9c
    steps:
    - name: Git checkout
      uses: actions/checkout@v4
    - name: Build kubectl
      uses: ./.github/actions/build
      with:
        app: kubectl
        version: ${{ matrix.version }}
        sha: ${{ matrix.sha }}

  awscli:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v4
    - name: Build awscli ${{ matrix.version }}
      uses: ./.github/actions/build
      with:
        app: awscli
        version: 2.33.31
        sha: 77b449774e7b35e2b4e83d9196e92ac7a13be007ed861f75a01ff9c8bcd653e6

  eks:
    needs: awscli
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - version: "1.35"
          - version: "1.34"
          - version: "1.33"
          - version: "1.32"
          - version: "1.31"
          - version: "1.30"
          - version: "1.29"
          - version: "1.28"
    steps:
    - name: Git checkout
      uses: actions/checkout@v4
    - name: Build eks
      uses: ./.github/actions/build
      with:
        app: eks
        version: ${{ matrix.version }}

  base:
    needs: awscli
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v4
    - name: Build base
      uses: ./.github/actions/build
      with:
        app: base
        version: 2.28

  ide:
    needs: base
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - version: "1.33"
          - version: "1.32"
          - version: "1.31"
          - version: "1.30"
          - version: "1.29"
          - version: "1.28"
    steps:
    - name: Git checkout
      uses: actions/checkout@v4
    - name: Build ide
      uses: ./.github/actions/build
      with:
        app: ide
        version: ${{ matrix.version }}
  didegithubrunner:
    needs: ide
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - version: "1.33"
          - version: "1.32"
          - version: "1.31"
    steps:
    - name: Git checkout
      uses: actions/checkout@v4
    - name: Build didegithubrunner
      uses: ./.github/actions/build
      with:
        app: didegithubrunner
        version: ${{ matrix.version }}