name: Build All

on: [push]

jobs:
  helm:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v1
    - name: Login
      run: |
        echo ${{ secrets.DOCKERHUB_PASSWORD }} | \
          docker login -u drmjo --password-stdin
    - name: 3.0.2
      env:
        SHA256SUM: c6b7aa7e4ffc66e8abb4be328f71d48c643cb8f398d95c74d075cfb348710e1d
        VERSION: 3.0.2
        APP: helm
      run: |
        make build
        make push
    - name: 2.16.1
      env:
        SHA256SUM: 7eebaaa2da4734242bbcdced62cc32ba8c7164a18792c8acdf16c77abffce202
        VERSION: 2.16.1
        APP: helm
      run: |
        make build
        make push
    - name: 2.15.2
      env:
        SHA256SUM: a9d2db920bd4b3d824729bbe1ff3fa57ad27760487581af6e5d3156d1b3c2511
        VERSION: 2.15.2
        APP: helm
      run: |
        make build
        make push
  kubectl:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v1
    - name: Login
      run: |
        echo ${{ secrets.DOCKERHUB_PASSWORD }} | \
          docker login -u drmjo --password-stdin
    - name: 1.16.4
      env:
        SHA256SUM: bbb2030487ba0570227a48c6faac1b09cad03748f5508c567d078d20feca2df2
        VERSION: 1.16.4
        APP: kubectl
      run: |
        make build
        make push
    - name: 1.15.7
      env:
        SHA256SUM: 01eb6cf747a0164a68df07fac2a50698bab51af0306d2797ed5971786fde9779
        VERSION: 1.15.7
        APP: kubectl
      run: |
        make build
        make push
    - name: 1.14.10
      env:
        SHA256SUM: 7729c6612bec76badc7926a79b26e0d9b06cc312af46dbb80ea7416d1fce0b36
        VERSION: 1.14.10
        APP: kubectl
      run: |
        make build
        make push
  appr:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v1
    - name: Login
      run: |
        echo ${{ secrets.DOCKERHUB_PASSWORD }} | \
          docker login -u drmjo --password-stdin
    - name: 0.7.4
      env:
        VERSION: 0.7.4
        SHA256SUM: 2ff148a900c5a153ea444bebac169001397ebfb466789356cd0f077b48e7d91c
        APP: appr
      run: |
        make build
        make push
  awscli:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v1
    - name: Login
      run: |
        echo ${{ secrets.DOCKERHUB_PASSWORD }} | \
          docker login -u drmjo --password-stdin
    - name: 1.16.309
      env:
        VERSION: 1.16.309
        APP: awscli
      run: |
        make build
        make push
  base:
    needs:
    - awscli
    - appr
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v1
    - name: Login
      run: |
        echo ${{ secrets.DOCKERHUB_PASSWORD }} | \
          docker login -u drmjo --password-stdin
    - name: base
      env:
        VERSION: buster
        AWS_CLI_VERSION: 1.16.309
        APP: base
      run: |
        make build
        make push