name: Build All

on: [push]

jobs:
  helm:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
    steps:
    - name: Git checkout
      uses: actions/checkout@v4
    - name: Build helm ${{ matrix.version }}
      uses: ./.github/actions/build
      with:
        app: helm
        version: 3.15.1
        sha: 7b20e7791c04ea71e7fe0cbe11f1a8be4a55a692898b57d9db28f3b0c1d52f11

  terragrunt:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
    steps:
    - name: Git checkout
      uses: actions/checkout@v4
    - name: Build terragrunt ${{ matrix.version }}
      uses: ./.github/actions/build
      with:
        app: terragrunt
        version: 0.58.14
        sha: 2abc9c2729a9a16c5672c3db71b333381d25fa44a978bba86dab2c0b3246b4de

  kubectl:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
    strategy:
      matrix:
        include:
          - version: 1.30.1
            sha: 5b86f0b06e1a5ba6f8f00e2b01e8ed39407729c4990aeda961f83a586f975e8a
          - version: 1.29.5
            sha: 603c8681fc0d8609c851f9cc58bcf55eeb97e2934896e858d0232aa8d1138366
          - version: 1.28.10
            sha: 389c17a9700a4b01ebb055e39b8bc0886330497440dde004b5ed90f2a3a028db
          - version: 1.27.14
            sha: 1d2431c68bb6dfa9de3cd40fd66d97a9ac73593c489f9467249eea43e9c16a1e
          - version: 1.26.13
            sha: e4bad4273431f9f5f05f27f5c2054cbbad6d9ee00b85e0810cb4ef0489b02571
          - version: 1.25.16
            sha: 5a9bc1d3ebfc7f6f812042d5f97b82730f2bdda47634b67bddf36ed23819ab17
    steps:
    - name: Git checkout
      uses: actions/checkout@v4
    - name: Build kubectl
      uses: ./.github/actions/build
      with:
        app: kubectl
        version: ${{ matrix.version }}
        sha: ${{ matrix.sha }}

  awscli:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
    steps:
    - name: Git checkout
      uses: actions/checkout@v4
    - name: Build awscli ${{ matrix.version }}
      uses: ./.github/actions/build
      with:
        app: awscli
        version: 2.16.4
        sha: 5b0c341f718c921f018791b2ba797470395bbc9c6c17c0b3f447910045fbc3c6

  eks:
    needs: awscli
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
    strategy:
      matrix:
        include:
          - version: "1.30"
          - version: 1.29
          - version: 1.28
          - version: 1.27
          - version: 1.26
          - version: 1.25
    steps:
    - name: Git checkout
      uses: actions/checkout@v4
    - name: Build eks
      uses: ./.github/actions/build
      with:
        app: eks
        version: ${{ matrix.version }}

  base:
    needs: awscli
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
    steps:
    - name: Git checkout
      uses: actions/checkout@v4
    - name: Build base
      uses: ./.github/actions/build
      with:
        app: base
        version: 2.16

  ide:
    needs: base
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
    strategy:
      matrix:
        include:
          - version: "1.30"
          - version: 1.29
          - version: 1.28
          - version: 1.27
          - version: 1.26
          - version: 1.25
    steps:
    - name: Git checkout
      uses: actions/checkout@v4
    - name: Build ide
      uses: ./.github/actions/build
      with:
        app: ide
        version: ${{ matrix.version }}
