name: Build All

on: [push]

jobs:
  helm:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v1
    - name: Login
      run: |
        echo ${{ secrets.DOCKERHUB_PASSWORD }} | \
          docker login -u drmjo --password-stdin
    - name: 3.0.2
      env:
        SHA256SUM: c6b7aa7e4ffc66e8abb4be328f71d48c643cb8f398d95c74d075cfb348710e1d
        VERSION: 3.0.2
        APP: helm
      run: bash build.sh
  kubectl:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v1
    - name: Login
      run: |
        echo ${{ secrets.DOCKERHUB_PASSWORD }} | \
          docker login -u drmjo --password-stdin
    - name: 1.16.4
      env:
        SHA256SUM: bbb2030487ba0570227a48c6faac1b09cad03748f5508c567d078d20feca2df2
        VERSION: 1.16.4
        APP: kubectl
      run: bash build.sh
    - name: 1.15.7
      env:
        SHA256SUM: 01eb6cf747a0164a68df07fac2a50698bab51af0306d2797ed5971786fde9779
        VERSION: 1.15.7
        APP: kubectl
      run: bash build.sh
    - name: 1.14.10
      env:
        SHA256SUM: 7729c6612bec76badc7926a79b26e0d9b06cc312af46dbb80ea7416d1fce0b36
        VERSION: 1.14.10
        APP: kubectl
      run: bash build.sh
  appr:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v1
    - name: Login
      run: |
        echo ${{ secrets.DOCKERHUB_PASSWORD }} | \
          docker login -u drmjo --password-stdin
    - name: 0.7.4
      env:
        VERSION: 0.7.4
        SHA256SUM: 2ff148a900c5a153ea444bebac169001397ebfb466789356cd0f077b48e7d91c
        APP: appr
      run: bash build.sh
  awscli:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v1
    - name: Login
      run: |
        echo ${{ secrets.DOCKERHUB_PASSWORD }} | \
          docker login -u drmjo --password-stdin
    - name: 1.16.314
      env:
        VERSION: 1.16.314
        # empty shasum
        SHA256SUM:
        APP: awscli
      run: bash build.sh
    - name: 1.18.56
      env:
        VERSION: 1.18.56
        # empty shasum
        SHA256SUM:
        APP: awscli
      run: bash build.sh
  eks:
    needs:
    - awscli
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v1
    - name: Login
      run: |
        echo ${{ secrets.DOCKERHUB_PASSWORD }} | \
          docker login -u drmjo --password-stdin
    - name: 1.16
      env:
        VERSION: 1.16
        APP: eks
      run: bash build.sh
    - name: 1.15
      env:
        VERSION: 1.15
        APP: eks
      run: bash build.sh
    - name: 1.14
      env:
        VERSION: 1.14
        APP: eks
      run: bash build.sh
  base:
    needs:
    - awscli
    - appr
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v1
    - name: Login
      run: |
        echo ${{ secrets.DOCKERHUB_PASSWORD }} | \
          docker login -u drmjo --password-stdin
    - name: base
      env:
        # this version should be the aws cli version
        VERSION: 1.18
        APP: base
      run: bash build.sh
  ide:
    needs:
    - base
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v1
    - name: Login
      run: |
        echo ${{ secrets.DOCKERHUB_PASSWORD }} | \
          docker login -u drmjo --password-stdin
    - name: 1.16
      env:
        VERSION: 1.16
        APP: ide
      run: bash build.sh
    - name: 1.15
      env:
        VERSION: 1.15
        APP: ide
      run: bash build.sh
    - name: 1.14
      env:
        VERSION: 1.14
        APP: ide
      run: bash build.sh