name: Build All

on: [push]

jobs:
  helm:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v1
    - name: Login
      run: |
        echo ${{ secrets.DOCKERHUB_PASSWORD }} | \
          docker login -u drmjo --password-stdin
    - name: 3.12.3
      env:
        SHA256SUM: 1b2313cd198d45eab00cc37c38f6b1ca0a948ba279c29e322bdf426d406129b5
        VERSION:  3.12.3
        APP: helm
      run: bash build.sh

  terragrunt:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v1
    - name: Login
      run: |
        echo ${{ secrets.DOCKERHUB_PASSWORD }} | \
          docker login -u drmjo --password-stdin
    - name: 0.50.8
      env:
        SHA256SUM: 5e8e233c8e4cabcbf12c09de3e13c2b1fba7e10da122799696b274de0ed518a8
        VERSION: 0.50.8
        APP: terragrunt
      run: bash build.sh

  kubectl:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v1
    - name: Login
      run: |
        echo ${{ secrets.DOCKERHUB_PASSWORD }} | \
          docker login -u drmjo --password-stdin
    - name: 1.28.1
      env:
        SHA256SUM: e7a7d6f9d06fab38b4128785aa80f65c54f6675a0d2abef655259ddd852274e1
        VERSION: 1.28.1
        APP: kubectl
      run: bash build.sh

    - name: 1.27.5
      env:
        SHA256SUM: 9a091fb65e4cf4e8be3ce9a21c79210177dd7ce31a2998ec638c92f37f058bcd
        VERSION: 1.27.5
        APP: kubectl
      run: bash build.sh

    - name: 1.26.8
      env:
        SHA256SUM: d8e0dba258d1096f95bb6746ca359db2ee8abe226e777f89dc8a5d1bb76795aa
        VERSION: 1.26.8
        APP: kubectl
      run: bash build.sh

    - name: 1.25.13
      env:
        SHA256SUM: 22c5d5cb95b671ea7d7accd77e60e4a787b6d40a6b8ba4d6c364cb3ca818c29a
        VERSION: 1.25.13
        APP: kubectl
      run: bash build.sh

    - name: 1.24.17
      env:
        SHA256SUM: 3e9588e3326c7110a163103fc3ea101bb0e85f4d6fd228cf928fa9a2a20594d5
        VERSION: 1.24.17
        APP: kubectl
      run: bash build.sh

  awscli:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v1
    - name: Login
      run: |
        echo ${{ secrets.DOCKERHUB_PASSWORD }} | \
          docker login -u drmjo --password-stdin
    - name: 2.13.13
      env:
        VERSION: 2.13.13
        SHA256SUM: 7204f9facf709ad8869a02d678cf67261668431460e67436cdfd239059a2ac8f
        APP: awscli
      run: bash build.sh
  eks:
    needs:
    - awscli
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v1
    - name: Login
      run: |
        echo ${{ secrets.DOCKERHUB_PASSWORD }} | \
          docker login -u drmjo --password-stdin
    - name: 1.28
      env:
        VERSION: 1.28
        APP: eks
      run: bash build.sh
    - name: 1.27
      env:
        VERSION: 1.27
        APP: eks
      run: bash build.sh
    - name: 1.26
      env:
        VERSION: 1.26
        APP: eks
      run: bash build.sh
    - name: 1.25
      env:
        VERSION: 1.25
        APP: eks
      run: bash build.sh
    - name: 1.24
      env:
        VERSION: 1.24
        APP: eks
      run: bash build.sh

  base:
    needs:
    - awscli
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v1
    - name: Login
      run: |
        echo ${{ secrets.DOCKERHUB_PASSWORD }} | \
          docker login -u drmjo --password-stdin
    - name: base
      env:
        # this version should be the aws cli version
        VERSION: 2.13
        APP: base
      run: bash build.sh
  ide:
    needs:
    - base
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v1
    - name: Login
      run: |
        echo ${{ secrets.DOCKERHUB_PASSWORD }} | \
          docker login -u drmjo --password-stdin
    - name: 1.28
      env:
        VERSION: 1.28
        APP: ide
      run: bash build.sh
    - name: 1.27
      env:
        VERSION: 1.27
        APP: ide
      run: bash build.sh
    - name: 1.26
      env:
        VERSION: 1.26
        APP: ide
      run: bash build.sh
    - name: 1.25
      env:
        VERSION: 1.25
        APP: ide
      run: bash build.sh
    - name: 1.24
      env:
        VERSION: 1.24
        APP: ide
      run: bash build.sh