name: Build All

on: [push]

env:
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

jobs:
  helm:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v4
    - name: Build helm ${{ matrix.version }}
      uses: ./.github/actions/build
      with:
        app: helm
        version: 3.18.6
        sha: 3f43c0aa57243852dd542493a0f54f1396c0bc8ec7296bbb2c01e802010819ce

  terragrunt:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v4
    - name: Build terragrunt ${{ matrix.version }}
      uses: ./.github/actions/build
      with:
        app: terragrunt
        version: 0.85.1
        sha: 7662eed6fa23cff352c996600c1cfdab085f19161cb6bd528e4125f31507f712

  kubectl:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - version: 1.33.0
            sha: 9efe8d3facb23e1618cba36fb1c4e15ac9dc3ed5a2c2e18109e4a66b2bac12dc
          - version: 1.32.3
            sha: ab209d0c5134b61486a0486585604a616a5bb2fc07df46d304b3c95817b2d79f
          - version: 1.31.5
            sha: fbecbfd375b3686002c2e81d51c390172f5ffba3d6b47920d55342cb03f557af
          - version: 1.30.2
            sha: c6e9c45ce3f82c90663e3c30db3b27c167e8b19d83ed4048b61c1013f6a7c66e
          - version: 1.29.6
            sha: 339553c919874ebe3b719e9e1fcd68b55bc8875f9b5a005cf4c028738d54d309
          - version: 1.28.11
            sha: 1dba63e1a5c9520fc516c6e817924d927b9b83b8e08254c8fe2a2edb65da7a9c
    steps:
    - name: Git checkout
      uses: actions/checkout@v4
    - name: Build kubectl
      uses: ./.github/actions/build
      with:
        app: kubectl
        version: ${{ matrix.version }}
        sha: ${{ matrix.sha }}

  awscli:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v4
    - name: Build awscli ${{ matrix.version }}
      uses: ./.github/actions/build
      with:
        app: awscli
        version: 2.28.14
        sha: fc41f9798bd3d22c47c51fd710812479c99b80dd740dacc11cb158f0e04ed9c6

  eks:
    needs: awscli
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - version: "1.33"
          - version: "1.32"
          - version: "1.31"
          - version: "1.30"
          - version: "1.29"
          - version: "1.28"
    steps:
    - name: Git checkout
      uses: actions/checkout@v4
    - name: Build eks
      uses: ./.github/actions/build
      with:
        app: eks
        version: ${{ matrix.version }}

  base:
    needs: awscli
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v4
    - name: Build base
      uses: ./.github/actions/build
      with:
        app: base
        version: 2.28

  ide:
    needs: base
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - version: "1.33"
          - version: "1.32"
          - version: "1.31"
          - version: "1.30"
          - version: "1.29"
          - version: "1.28"
    steps:
    - name: Git checkout
      uses: actions/checkout@v4
    - name: Build ide
      uses: ./.github/actions/build
      with:
        app: ide
        version: ${{ matrix.version }}
