name: Build All

on: [push]

jobs:
  helm:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v1
    - name: Login
      run: |
        echo ${{ secrets.DOCKERHUB_PASSWORD }} | \
          docker login -u drmjo --password-stdin
    - name: 3.1.3
      env:
        SHA256SUM: 7ca15cb5e3a76393eccd7389f2b3d20082b8c535b6689882613bfcc4a7d07c23
        VERSION: 3.1.3
        APP: helm
      run: bash build.sh
  kubectl:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v1
    - name: Login
      run: |
        echo ${{ secrets.DOCKERHUB_PASSWORD }} | \
          docker login -u drmjo --password-stdin
    - name: 1.18.8
      env:
        SHA256SUM: a076f5eff0710de94d1eb77bee458ea43b8f4d9572bbb3a3aec1edf0dde0a3e7
        VERSION: 1.18.8
        APP: kubectl
      run: bash build.sh
    - name: 1.17.5
      env:
        SHA256SUM: 03cd1fa19f90d38005148793efdb17a9b58d01dedea641a8496b9cf228db3ab4
        VERSION: 1.17.5
        APP: kubectl
      run: bash build.sh
    - name: 1.16.9
      env:
        SHA256SUM: 0f3a6618a2e7402b11a1d9b9ffeff3ba0c6765dc361815413ce7441799aecf96
        VERSION: 1.16.9
        APP: kubectl
      run: bash build.sh
    - name: 1.15.12
      env:
        SHA256SUM: a32b762279c33cb8d8f4198f3facdae402248c3164e9b9b664c3afbd5a27472e
        VERSION: 1.15.12
        APP: kubectl
      run: bash build.sh
    - name: 1.14.10
      env:
        SHA256SUM: 7729c6612bec76badc7926a79b26e0d9b06cc312af46dbb80ea7416d1fce0b36
        VERSION: 1.14.10
        APP: kubectl
      run: bash build.sh
  appr:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v1
    - name: Login
      run: |
        echo ${{ secrets.DOCKERHUB_PASSWORD }} | \
          docker login -u drmjo --password-stdin
    - name: 0.7.4
      env:
        VERSION: 0.7.4
        SHA256SUM: 2ff148a900c5a153ea444bebac169001397ebfb466789356cd0f077b48e7d91c
        APP: appr
      run: bash build.sh
  awscli:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v1
    - name: Login
      run: |
        echo ${{ secrets.DOCKERHUB_PASSWORD }} | \
          docker login -u drmjo --password-stdin
    - name: 1.18.223
      env:
        VERSION: 1.18.223
        # empty shasum
        SHA256SUM:
        APP: awscli
      run: bash build.sh
    - name: 1.19.1
      env:
        VERSION: 1.19.1
        # empty shasum
        SHA256SUM:
        APP: awscli
      run: bash build.sh
  eks:
    needs:
    - awscli
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v1
    - name: Login
      run: |
        echo ${{ secrets.DOCKERHUB_PASSWORD }} | \
          docker login -u drmjo --password-stdin
    - name: 1.18
      env:
        VERSION: 1.18
        APP: eks
      run: bash build.sh
    - name: 1.17
      env:
        VERSION: 1.17
        APP: eks
      run: bash build.sh
    - name: 1.16
      env:
        VERSION: 1.16
        APP: eks
      run: bash build.sh
    - name: 1.15
      env:
        VERSION: 1.15
        APP: eks
      run: bash build.sh
  base:
    needs:
    - awscli
    - appr
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v1
    - name: Login
      run: |
        echo ${{ secrets.DOCKERHUB_PASSWORD }} | \
          docker login -u drmjo --password-stdin
    - name: base
      env:
        # this version should be the aws cli version
        VERSION: 1.19
        APP: base
      run: bash build.sh
  ide:
    needs:
    - base
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v1
    - name: Login
      run: |
        echo ${{ secrets.DOCKERHUB_PASSWORD }} | \
          docker login -u drmjo --password-stdin
    - name: 1.18
      env:
        VERSION: 1.18
        APP: ide
      run: bash build.sh
    - name: 1.17
      env:
        VERSION: 1.17
        APP: ide
      run: bash build.sh
    - name: 1.16
      env:
        VERSION: 1.16
        APP: ide
      run: bash build.sh
    - name: 1.15
      env:
        VERSION: 1.15
        APP: ide
      run: bash build.sh
